[package]
name = "randr"
version = "0.2.0"
authors = ["Michael Lodder <redmike7@gmail.com>"]
edition = "2021"

[dependencies]
arrayref = "0.3.5"
atty = "0.2.13"
clap = "2.34"
serious = { version = "0.2", path = "../serious" }
rand = "0.8"
rand_chacha = "0.3"
rpassword = "7"
sha2 = "0.10"
